version: '3.8'

services:
  app-eggs-count:
    build: .
    ports:
      - "${PORT_APP}:${PORT_APP}"
    depends_on:
      - database-eggs-count
  
    links:
      - "database-eggs-count:${HOST}"
    networks:
      - eggs-network
    restart: always
  

  database-eggs-count:
    image: postgres:15-alpine
    volumes:
      - fiocruz-eggs-count:/var/lib/postgresql/data
    restart: always
    networks:
      - eggs-network

volumes:
  fiocruz-eggs-count:

networks:
  eggs-network:
    driver: bridge
