version: '3.8'

services:
  app-eggs-count:
    build: .
    ports:
      - "${PORT_APP}:${PORT_APP}"
    depends_on:
      - database-eggs-count
      - python_server
    links:
      - "database-eggs-count:${HOST}"
    networks:
      - eggs-network
    restart: always
  
  python_server:
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - eggs-network

  database-eggs-count:
    image: postgres:15-alpine
    expose:
      - "5432"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - fiocruz-eggs-count:/var/lib/postgresql/data
    networks:
      - eggs-network

volumes:
  fiocruz-eggs-count:

networks:
  eggs-network:
    driver: bridge
