version: '3'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DATABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_POSTGRES_DB}
    ports:
      - '5432:5432'
    expose:
      - '5432'
